version: "3"
services:
  python:
    build: ./
    image: atcoder
    container_name: atcoder
    tty: true
    working_dir: /atcoder_python
    volumes: 
      - ../../atcoder_python:/atcoder_python
    